name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install EB CLI
        run: pip install awsebcli

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm ci

      - name: Build API
        run: npx nx build api --prod

      - name: Build App
        run: npx nx build --prod

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Initialise Elastic Beanstalk
        run: |
          cd dist/apps/api
          eb init TomatoesAPI --region ap-southeast-2 --platform 'Node.js 16 running on 64bit Amazon Linux 2'

      - name: Deploy API to Elastic Beanstalk
        run: |
          cd dist/apps/api
          eb deploy Tomatoesapi-env

      - name: Copy to S3
        run: aws s3 sync --delete ./dist/apps/tomatoes-app s3://tomatoescloudfrontbucket

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id E19SD6HAYG85F3 --paths '/*'
